# Generated by Django 4.0.5 on 2022-07-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_message_body_message_created_message_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
