# Generated by Django 4.0.5 on 2022-07-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='participant',
            new_name='participants',
        ),
    ]
