# Generated by Django 4.0.6 on 2022-07-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
